# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-29 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0002_auto_20181230_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='projects',
            new_name='Project',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
